# Generated by Django 3.1.6 on 2021-02-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_auto_20210213_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
